# Site
name: 'THiCC Lab'
description: 'THiCC Lab Website'
logo: 'assets/images/logo.png'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: ''
disqus: 'demowebsite'
email: 'cld5070@psu.edu'
mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    dancy:
      name:           Dr. Christopher L. Dancy
      site:           https://github.com/cld5070
      avatar:         /assets/images/avatar1.jpg
      bio:            Dr. Chris Dancy interest and expertise lies at the intersections of human behavior, computational systems, and sociocultural structures. He uses theoretical perspectives from computational cognitive science and Black studies to ground his research at these intersections. To study the processes that define these interactions, Dr. Dancy uses computational cognitive modeling, human behavioral studies, and design & implementation considerations of computational (particularly “AI”) systems.
      email:          cld5070@psu.edu
      twitter:        https://github.com/cld5070

    deja:
      name:           Deja
      site:           https://github.com/cld5070
      avatar:         /assets/images/avatar1.jpg
      bio:            Deja Workman is a PhD student in Information Sciences and Technology at Penn State and a graduate research assistant in THiCC Lab. In 2022 she graduated from Penn State with a B.S. in information sciences and technology. Her current research project focuses on anti-blackness in the artificial intelligence development process, and her past research projects include testing learning theories on complex tasks as well as diversity in STEM education and inclusive instructor behaviors.
      email:          cld5070@psu.edu
      twitter:        https://github.com/cld5070

    meera:
      name:           Meera
      site:           https://github.com/cld5070
      avatar:         /assets/images/avatar1.jpg
      bio:            Meera Ray is a first year PhD student in Computer Science and Engineering at Penn State and a graduate research assistant in THiCC Lab. She graduated with a B.S. in Statistics and Machine Learning from Carnegie Mellon in 2023. Her research aims to articulate how artificial intelligence interacts with social hierarchies. Meera’s current research project, developing a cognitive model of human decision making in disaster situations, is with the AI Institute for Societal Decision Making (AI-SDM).
      email:          cld5070@psu.edu
      twitter:        https://github.com/cld5070

    swapnika:
      name:           Swapnika
      site:           https://github.com/cld5070
      avatar:         /assets/images/avatar1.jpg
      bio:            Swapnika Dulam is a Second year Masters student in Computer Science at Penn State and a Graduate Research Assistant in THiCC Lab. She is from India and did her Integrated Dual Degree (B.Tech + M.Tech (CSE)) in JNTUHCEH, Hyderabad, India. She has four years of industry experience as a full stack developer and also designed distributed systems using Restful API. Her Current research project focuses on Human AI Interaction where she is working on Minecraft malmo environment.
      email:          cld5070@psu.edu
      twitter:        https://github.com/cld5070

    haya:
      name:           Haya
      site:           https://github.com/cld5070
      avatar:         /assets/images/avatar1.jpg
      bio:            Haya Alshayji is currently advancing her academic journey as a Ph.D. candidate at Pennsylvania State University’s College of Engineering, with a focus on integrating machine learning, data science, and statistical modeling in her studies. Recently, she expanded her research experience by joining THiCC Lab as a research assistant. For three years, she has been an active member of the Artificial Intelligence Lab, where she has been instrumental in cross-disciplinary research projects, particularly in applying AI techniques to address healthcare disparities. Haya’s involvement in these diverse research areas highlights her commitment to leveraging AI for social good and advancing the field of data science.
      email:          cld5070@psu.edu
      twitter:        https://github.com/cld5070

    ayush:
      name:           Ayush
      site:           https://github.com/cld5070
      avatar:         /assets/images/avatar1.jpg
      bio:            Ayush Tanwar is a 1st year MS student in Computer Science and Engineering.
      email:          cld5070@psu.edu
      twitter:        https://github.com/cld5070
 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: dr-christopher-l-dancy
      avatar: /assets/images/avatar1.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10

# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]