# Site
name: 'THiCC Lab'
description: 'THiCC Lab Website'
logo: 'assets/images/logo.png'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: ''
disqus: 'demowebsite'
email: 'cld5070@psu.edu'
mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    sage:
      name:           Sage
      site:           https://github.com/sdp5550
      avatar:         /assets/images/avatar1.jpg
      bio:            "Hi, I am Sage, the original author of this website. I hope you like it!"
      email:          sdp5550@psu.edu
      twitter:        https://github.com/sdp5550

    dancy:
      name:           Dr. Dancy
      site:           https://github.com/cld5070
      avatar:         /assets/images/avatar1.jpg
      bio:            The GOAT
      email:          cld5070@psu.edu
      twitter:        https://github.com/cld5070
 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: sage
      avatar: /assets/images/avatar1.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]